// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Web.Data;

namespace Web.Migrations
{
    [DbContext(typeof(ToolkitContext))]
    [Migration("20171222054855_initialharddisk")]
    partial class initialharddisk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Models.HardDisk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bank");

                    b.Property<string>("BarCode");

                    b.Property<string>("Category");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Tag");

                    b.HasKey("ID");

                    b.ToTable("HardDisk");
                });
#pragma warning restore 612, 618
        }
    }
}
